name: React CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Start server
        run: npm start &

      - name: Wait for server to start
        run: npx wait-on http://localhost:3000

      - name: Run tests
        run: npm test

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run api/Github_Actions.postman_collection.json

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ViniciusONevesRodrigues_Github-Actions-Activity
            -Dsonar.organization=viniciusonevesrodrigues
            -Dsonar.host.url=https://sonarcloud.io

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Scan
        run: snyk test --org=viniciusonevesrodrigues --project-name=Github-Actions-Activity

      - name: Upload Snyk report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk-report.json

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
