name: React CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Install SonarScanner
        run: |
          curl -sSLo /tmp/sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip /tmp/sonar-scanner-cli.zip -d /tmp
          export PATH=/tmp/sonar-scanner-4.6.2.2472-linux/bin:$PATH

      - name: Run SonarScanner
        run: |
          /tmp/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
          -Dsonar.projectKey=ViniciusONevesRodrigues_Github-Actions-Activity \
          -Dsonar.organization=viniciusonevesrodrigues \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN



